version: "3"
volumes:
  app-cache:
    driver: local

services:
  client:
    container_name: dalle_client_react
    image: dalle_client_react:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    # restart: always
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
  server:
    container_name: dalle_server_flask
    image: dalle_server_flask:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - app-cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]