version: "3"
volumes:
  app-cache:
    driver: local

services:
  dalle-mini-flaskapp:
    container_name: dalle_mini_flaskapp
    image: dalle_mini_flaskapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - app-cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              device_ids: ["0"]
              capabilities: ["gpu"]